### ISSUE TITLE
AWS - 3rd cluster created, but not mentioned...by design or needs adjusted? 

### ISSUE THREAD

**Issue by rabeyta** [vmware-tanzu/service-installer-for-vmware-tanzu#20]
Referencing the following: 
The goals: 
https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/aws/README.md?plain=1#L9-L13

the way the repo is setup

In the main.tf, we create 1 mgmt VPC with a cluster in it and 1 workload VPC with a cluster in it
https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/aws/main.tf#L51-L77

these get created as expected due mgmt cluster explicitly being created and looping over the workload cluster configs in the script.
https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/aws/tkg_vpc/script.sh#L181

the question i have is on this line in the loop when the mgmt config is found.
```
if [[ "$NO_YAML_NAME" == "vpc-config-mgmt" ]]; then
        setup_cluster $i tkg-wl-aws
```

we have already created the management cluster based on `vpc-config-mgmt.yaml`.

this line then creates a 2nd workload cluster with a hard coded name using the mgmt cluster's configuration, which puts the workload cluster in the mgmt cluster's vpc, vs the prior created workload vpc.

My question comes down to the intent and a solve:
1. Did i miss a documented step or ref arch expectation? 
2. Should that line be replaced with an `echo` or similar no-op to remove the extra cluster creation? That cluster currently has a hard coded name that is not configurable without editing the script prior to running the terraform apply.
3. Does the repo need updated to allow creating a cluster and not a new VPC? (Allowing a workload cluster defined for an existing VPC)
4. both 2+3? 
5. Does this behavior need documented only? 
6. ??

I feel number 2 is appropriate in the near term as it isn't much work and maybe 3 is a future feature enhancement?

what are your thoughts?

**Comment by tasmiya-bano** [comment]
Fixed documentation
