### ISSUE TITLE
AVI Vault link does not contain reference to 20.1.7 anymore

### ISSUE THREAD

**Issue by bbertka-pivotal** [vmware-tanzu/service-installer-for-vmware-tanzu#21]
The instructions for obtaining Avi 20.1.7 says to navigate to vault page, however 20.1.7 is not there anymore.  Perhaps direct user to find OVA at https://marketplace.cloud.vmware.com/services/details/nsx-advanced-load-balancer-1?slug=true.

**Comment by tasmiya-bano** [comment]
This is fixed as part of c77048d89a2a69c84ebf4d75c059efb4f2c74252 commit. Hence closing the issue.
