### ISSUE TITLE
'int is not iterable' when an invalid TMC token is provided

### ISSUE THREAD

**Issue by carlosonunez-vmw** [vmware-tanzu/service-installer-for-vmware-tanzu#38]
## What happened?

I got the message above when I provided an incorrect TMC token with no additional information.

## How to reproduce

1. Start the Service Installer UI.
2. Provide a TMC refresh token when prompted that is invalid

## What should happen?

The UI should tell me that the token is invalid, or an error message if one is provided.

## What actually happens?

`int is not iterable`

## Additional notes

**Comment by carlosonunez-vmw** [comment]
Thanks!

**Comment by ksahilvmware** [comment]
Changes has been merged for this issue.
