### ISSUE TITLE
SIVT does not fetch vSphere Datastore full path correctly

### ISSUE THREAD

**Issue by tsugliani** [vmware-tanzu/service-installer-for-vmware-tanzu#46]
**Bug description**

IHAC using Storage Folders in vCenter, and SIVT does not cope with folder path, when configuring TKGm (jinja templates for the key `VSPHERE_DATASTORE`)

<img width="888" alt="Screenshot 2022-07-07 at 16 35 09" src="https://user-images.githubusercontent.com/146306/177803249-5f57d94f-845d-4b7f-8147-a99441225fc2.png">

<img width="331" alt="Screenshot 2022-07-07 at 16 35 46" src="https://user-images.githubusercontent.com/146306/177805876-52af55a1-b897-4d59-bf76-fb2e539268d3.png">

I found 2 places in the code where this is done while testing and this fixed my issue, it's a harcoded fix obviously we need to fetch this properly, and store it.

https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/src/vsphere/managementConfig/vsphere_management_config.py#L2067

https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/src/vsphere/managementConfig/vsphere_management_config.py#L2212

my dirty fix to unstuck us 

`datastore_path = "/" + datacenter + "/datastore/vSAN Storages/" + datastoreName`

**Affected product modules (please put an X in all that apply)**

- [x] SIVT APIs
- [x] SIVT UI
- [X] SIVT CLI
- [ ] Docs

**Expected behavior**

When using the UI, and being at the vCenter Connection step/credentials:
- It will load all the required information, but for vSphere Datastore it will only keep the datastore name assuming it's at the root level in vCenter.

**Steps to reproduce the bug**

- Put a vSphere Datastore in any folder
- arcas deployment
- arcas should deploy AVI Controller correctly
- arcas will fail deploying TKGm vSphere VM with an error stating it cannot find the Datastore.

**Version** (include the SHA if the version is not obvious)

NA 

**Environment where the bug was observed (vSphere+VMC, vSphere+DVS, vSphere+NSXt, etc)**

vSphere+DVS

- SIVT version: 1.2.0
- vSphere version: 6.7u3
- vCenter version: 6.7u3
- Kubernetes version: (use `kubectl version`): from SIVT-1.2.0
- Kubernetes installer & version: from SIVT-1.2.0
- Cloud provider or hardware configuration: NA
- OS (e.g. from `/etc/os-release`): from SIVT-1.2.0
- Sonobuoy tarball (which contains * below)

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by rashikwal** [comment]
The fix has been made and will be available in SIVT 1.3 release
