### ISSUE TITLE
Broken link to TKO ref architecture

### ISSUE THREAD

**Issue by rodrigocavmw** [vmware-tanzu/service-installer-for-vmware-tanzu#7]
In the first section of the readme.md inside https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/tree/1.1-1.5.1/azure there is a link 'Based on the Reference Architecture, TKO on Azure Hybrid-Cloud' that is broken.

https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/src/reference-designs/tko-on-azure-hybrid.md

It seems that the correct URL is this --> https://github.com/gradinDotCom/tanzu-validated-solutions/blob/tko-azure-hybrid/src/reference-designs/tko-on-azure.md.

Thanks, Rodrigo.

**Comment by tasmiya-bano** [comment]
@z4ce has already fixed this and created Pull request. @rodrigocavmw Please confirm if we are good to close this case ?

**Comment by tasmiya-bano** [comment]
Pull request by @z4ce of this fix is merged. Hence, closing the issue.

**Comment by rodrigocavmw** [comment]
Thanks team for the collaboration!
