### ISSUE TITLE
"Deploying VMware Tanzu for Kubernetes Operations on vSphere with vSphere Distributed Switch Using Service Installer for VMware Tanzu" page have an internal VMware link

### ISSUE THREAD

**Issue by dineshtripathi30** [vmware-tanzu/service-installer-for-vmware-tanzu#8]
**Bug description**
https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/docs/product/release/vSphere%20-%20Backed%20by%20VDS/TKGm/TKOonVsphereVDStkg.md#deploying-vmware-tanzu-for-kubernetes-operations-on-vsphere-with-vsphere-distributed-switch-using-service-installer-for-vmware-tanzu 

Above page have an internal VMware vault link reference under Pre-requirement section below
Upload the NSX Advanced Load Balancer Controller in Content Library:
Download the NSX Advanced Load Balancer 20.1.7 OVA from [VMware Vault]**_(https://vault.vmware.com/group/nsx/avi-networks-technical-resources)._**

**Expected behavior**
We should have an external link as external user can not access them.

**Steps to reproduce the bug**
- Click on the link below
https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/docs/product/release/vSphere%20-%20Backed%20by%20NSX-T/tkoVsphereNSXT.md#deploying-vmware-tanzu-for-kubernetes-operations-on-vsphere-with-nsx-t-using-service-installer-for-vmware-tanzu
- Go to Pre-req section and look for text "Download the NSX Advanced Load Balancer 20.1.7 OVA from [VMware Vault](https://vault.vmware.com/group/nsx/avi-networks-technical-resources)." 

**Version** (include the SHA if the version is not obvious)
1.1.1

**Environment where the bug was observed (vSphere+VMC, vSpshere+DVS, vSphere+NSXt, etc)**
NA
- Service Installer for VMware Tanzu version: 1.1.1
- vSpshere version: NA
- vCenter version:  NA
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by tasmiya-bano** [comment]
Updated the document with MarketPlace link as pat of c77048d89a2a69c84ebf4d75c059efb4f2c74252 commit. Hence, closing this issue.
