### ISSUE TITLE
"https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/docs/product/release/vSphere%20-%20Backed%20by%20NSX-T/tkoVsphereNSXT.md#deploying-vmware-tanzu-for-kubernetes-operations-on-vsphere-with-nsx-t-using-service-installer-for-vmware-tanzu" page have an incorrect info 

### ISSUE THREAD

**Issue by dineshtripathi30** [vmware-tanzu/service-installer-for-vmware-tanzu#9]
**Bug description**
Picture shows that the shared services cluster should be on a different network segment but under pre-requirement section (point 1), says that shared services cluster should be on the same management network.

**Expected behavior**
Pre-requirement should be updated to reflect the picture networking. 

**Steps to reproduce the bug**
- Open page "https://github.com/vmware-tanzu/service-installer-for-vmware-tanzu/blob/main/docs/product/release/vSphere%20-%20Backed%20by%20NSX-T/tkoVsphereNSXT.md#deploying-vmware-tanzu-for-kubernetes-operations-on-vsphere-with-nsx-t-using-service-installer-for-vmware-tanzu" and look for point 1 under pre-requirements

**Version** (include the SHA if the version is not obvious)
SIVT 

**Environment where the bug was observed (vSphere+VMC, vSpshere+DVS, vSphere+NSXt, etc)**
vSphere with NSXT
- Service Installer for VMware Tanzu version: 1.1.1
- vSpshere version: Na
- vCenter version: NA
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by tasmiya-bano** [comment]
@dineshtripathi30 Thanks for reporting this, documentation is updated as part c77048d89a2a69c84ebf4d75c059efb4f2c74252 commit.
